[phases. setup]
nixPkgs = ['php82', 'php82Extensions. pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.mysqli', 'php82Extensions.mbstring', 'php82Extensions. xml', 'php82Extensions.curl', 'php82Extensions.zip', 'php82Extensions.bcmath']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader --no-interaction']

[phases.build]
cmds = ['php artisan config:cache', 'php artisan route:cache']

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'